### ISSUE TITLE
Causes normal tableView scrolling else where in an app to be slow

### ISSUE THREAD

**Issue by domness** [mikefrederick/MFSideMenu#4]
After adding the side menu, all my other table views lag. They went from buttery smooth to incredibly horrible to scroll.

**Comment by mikefrederick** [comment]
@domness what version of iOS are you seeing this in? Any chance you could supply a demo of this happening? Someone else reported this issue as well but I haven't been able to replicate it.

**Comment by schnettker** [comment]
## I found a solution on cocoacontrols.com

"controller.view.layer.shadowPath = [UIBezierPath bezierPathWithRect:controller.view.bounds].CGPath;" on the Method : "+ (void) configureWithNavigationController:(UINavigationController *)controller 
sideMenuController:(id)menuController" in MFSideMenuManager.m class.

**Comment by zjxhz** [comment]
Sorry for opening this discussion again, I know it's an old issue which has been already closed. But I had this problem long ago, and fixed it in a similar way(some issue related to shadow), but now I'm wondering why was the issue and why the change above fixed it?

I asked this because I need to prepare the knowledge for future interviews. The code of MFMenu has changed a lot since then and it's difficult for me to trace back...
